import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useMemo, useRef, useState } from "react";
import { Archive, BarChart3, FileDown, FilePlus2, FolderOpen, Image, KeyRound, LockKeyhole, Pencil, Plus, Search, ShieldAlert, Users } from "lucide-react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { supabase } from "@/integrations/local-db/client";
import { fetchAllRows } from "@/lib/fetch-all";
import { createProtection, decryptFile, decryptJson, encryptFile, encryptJson, type OcorrenciasProtection, unlockProtection } from "@/lib/ocorrencias-crypto";
import { exportOcorrenciaPDF } from "@/lib/export-ocorrencia";

export const Route = createFileRoute("/_authenticated/ocorrencias")({ component: Ocorrencias });

type Person = { id: string; nome: string; tipo: "Colaborador terceirizado" | "Pessoa externa" | "Outro"; observacao?: string; foto?: FileInfo };
type FileInfo = { id: string; nome: string; tipo: string; storagePath: string; imagem?: boolean };
type Occurrence = { id: string; protocolo: string; data: string; local: string; categoria: string; status: "Em análise" | "Encaminhada" | "Encerrada" | "Arquivada"; relato: string; encaminhamentos: string; pessoas: Person[]; evidencias: FileInfo[]; historico: { data: string; texto: string }[]; createdAt: string; updatedAt: string };
type StoredOccurrence = { id: string; payload: string; created_at: string; updated_at: string };

const categories = ["Pesca não autorizada", "Caça não autorizada", "Extração irregular", "Desvio de insumos", "Revista veicular", "Invasão", "Outro"];
const statuses: Occurrence["status"][] = ["Em análise", "Encaminhada", "Encerrada", "Arquivada"];
const now = () => new Date().toISOString();
const emptyOccurrence = (): Occurrence => ({ id: crypto.randomUUID(), protocolo: `OC-${new Date().toISOString().slice(0, 10).replaceAll("-", "")}-${Math.random().toString(36).slice(2, 6).toUpperCase()}`, data: new Date().toISOString().slice(0, 10), local: "", categoria: "", status: "Em análise", relato: "", encaminhamentos: "", pessoas: [], evidencias: [], historico: [{ data: now(), texto: "Registro criado" }], createdAt: now(), updatedAt: now() });

function countBy(items: Occurrence[], get: (item: Occurrence) => string) { return Array.from(items.reduce((map, item) => map.set(get(item) || "Não informado", (map.get(get(item) || "Não informado") ?? 0) + 1), new Map<string, number>()).entries()).map(([name, total]) => ({ name, total })).sort((a, b) => b.total - a.total); }

function Ocorrencias() {
  const [protection, setProtection] = useState<OcorrenciasProtection | null | undefined>(undefined);
  const [key, setKey] = useState<CryptoKey | null>(null);
  const [password, setPassword] = useState(""); const [confirmation, setConfirmation] = useState("");
  const [items, setItems] = useState<Occurrence[]>([]); const [loading, setLoading] = useState(false);
  const [selected, setSelected] = useState<string | null>(null); const [newOpen, setNewOpen] = useState(false); const [filter, setFilter] = useState(""); const [statusFilter, setStatusFilter] = useState("ativos");
  const [draft, setDraft] = useState<Occurrence>(emptyOccurrence); const [personDraft, setPersonDraft] = useState<Person>({ id: "", nome: "", tipo: "Pessoa externa", observacao: "" });
  const [photos, setPhotos] = useState<Record<string, string>>({}); const [viewer, setViewer] = useState<{ title: string; url: string } | null>(null); const [exportOpen, setExportOpen] = useState(false); const [includePersonPhotos, setIncludePersonPhotos] = useState(false); const [includeEvidencePhotos, setIncludeEvidencePhotos] = useState(false); const [photoTarget, setPhotoTarget] = useState<string | null>(null); const [editing, setEditing] = useState(false); const [editDraft, setEditDraft] = useState<Occurrence | null>(null);
  const photoInput = useRef<HTMLInputElement>(null); const evidenceInput = useRef<HTMLInputElement>(null);

  const loadProtection = async () => { const { data, error } = await supabase.from("ocorrencias_protecao" as never).select("*").eq("id", "principal"); if (error) toast.error(error.message); setProtection(((data ?? [])[0] as OcorrenciasProtection | undefined) ?? null); };
  useEffect(() => { void loadProtection(); }, []);
  const load = async (activeKey = key) => { if (!activeKey) return; setLoading(true); try { const rows = await fetchAllRows<StoredOccurrence>(() => supabase.from("ocorrencias" as never).select("*").order("updated_at", { ascending: false }) as never); const parsed = await Promise.all(rows.map(async (row) => ({ ...(await decryptJson<Occurrence>(row.payload, activeKey)), id: row.id }))); setItems(parsed.sort((a, b) => b.updatedAt.localeCompare(a.updatedAt))); } catch (error) { toast.error("Não foi possível abrir os registros protegidos: " + (error as Error).message); } finally { setLoading(false); } };
  useEffect(() => { if (key) void load(key); }, [key]);
  const setup = async () => { if (password !== confirmation) return toast.error("As senhas não coincidem"); try { const result = await createProtection(password); const { error } = await supabase.from("ocorrencias_protecao" as never).upsert([result.protection] as never, { onConflict: "id" }); if (error) throw new Error(error.message); setKey(result.key); setProtection(result.protection); setPassword(""); setConfirmation(""); toast.success("Proteção criada. A senha não é armazenada pelo SPGuard."); } catch (e) { toast.error((e as Error).message); } };
  const unlock = async () => { if (!protection) return; try { setKey(await unlockProtection(protection, password)); setPassword(""); } catch (e) { toast.error((e as Error).message); } };
  const persist = async (item: Occurrence) => { if (!key) return; const updated = { ...item, updatedAt: now() }; const { error } = await supabase.from("ocorrencias" as never).upsert([{ id: updated.id, payload: await encryptJson(updated, key), created_at: updated.createdAt, updated_at: updated.updatedAt }] as never, { onConflict: "id" }); if (error) throw new Error(error.message); setItems((old) => [updated, ...old.filter((x) => x.id !== updated.id)]); setSelected(updated.id); return updated; };
  const saveNew = async () => { if (!draft.local.trim() || !draft.categoria.trim() || !draft.relato.trim()) return toast.error("Informe local, categoria e relato factual"); try { await persist(draft); setNewOpen(false); setDraft(emptyOccurrence()); toast.success("Ocorrência registrada localmente"); } catch (e) { toast.error((e as Error).message); } };
  const selectedItem = items.find((item) => item.id === selected) ?? null;
  const shown = useMemo(() => items.filter((item) => { const text = `${item.protocolo} ${item.local} ${item.categoria} ${item.relato}`.toLowerCase(); return (!filter || text.includes(filter.toLowerCase())) && (statusFilter === "todos" || statusFilter === "ativos" ? (statusFilter !== "ativos" || item.status !== "Arquivada") : item.status === statusFilter); }), [items, filter, statusFilter]);
  const stats = useMemo(() => countBy(items.filter((item) => item.status !== "Arquivada"), (item) => item.categoria), [items]);
  useEffect(() => { if (!selectedItem || !key) return; let valid = true; const urls: string[] = []; void (async () => { const next: Record<string, string> = {}; for (const person of selectedItem.pessoas) if (person.foto) { try { const { data } = await supabase.storage.from("ocorrencia-evidencias").createSignedUrl(person.foto.storagePath, 60); if (!data) continue; const raw = await fetch(data.signedUrl); const blob = await decryptFile(await raw.blob(), key, person.foto.tipo); URL.revokeObjectURL(data.signedUrl); const url = URL.createObjectURL(blob); urls.push(url); next[person.id] = url; } catch { /* arquivo indisponível permanece sem miniatura */ } } if (valid) setPhotos(next); }); return () => { valid = false; urls.forEach(URL.revokeObjectURL); }; }, [selectedItem?.id, selectedItem?.updatedAt, key]);
  const upload = async (file: File, occurrenceId: string, kind: "pessoa" | "evidencia") => { if (!key) throw new Error("Área bloqueada"); if (file.size > 50 * 1024 * 1024) throw new Error("O arquivo excede 50 MB"); const id = crypto.randomUUID(); const path = `${occurrenceId}/${id}.bin`; const encrypted = await encryptFile(file, key); const sent = await supabase.storage.from("ocorrencia-evidencias").upload(path, new File([encrypted], `${id}.bin`, { type: "application/octet-stream" })); if (sent.error) throw new Error(sent.error.message); const { error } = await supabase.from("ocorrencia_arquivos" as never).upsert([{ id, ocorrencia_id: occurrenceId, storage_path: path, created_at: now(), updated_at: now() }] as never, { onConflict: "id" }); if (error) throw new Error(error.message); return { id, nome: file.name, tipo: file.type || "application/octet-stream", storagePath: path, imagem: kind === "pessoa" || file.type.startsWith("image/") } as FileInfo; };
  const addPerson = async () => { if (!selectedItem || !personDraft.nome.trim()) return toast.error("Informe o nome da pessoa"); const person = { ...personDraft, id: crypto.randomUUID() }; try { await persist({ ...selectedItem, pessoas: [...selectedItem.pessoas, person], historico: [...selectedItem.historico, { data: now(), texto: `Pessoa vinculada: ${person.nome}` }] }); setPersonDraft({ id: "", nome: "", tipo: "Pessoa externa", observacao: "" }); toast.success("Pessoa vinculada"); } catch (e) { toast.error((e as Error).message); } };
  const uploadPersonPhoto = async (file?: File) => { if (!selectedItem || !file || !photoTarget) return; const person = selectedItem.pessoas.find((item) => item.id === photoTarget); if (!person) return toast.error("Pessoa não encontrada"); try { const photo = await upload(file, selectedItem.id, "pessoa"); const preview = URL.createObjectURL(file); setPhotos((old) => ({ ...old, [person.id]: preview })); await persist({ ...selectedItem, pessoas: selectedItem.pessoas.map((p) => p.id === person.id ? { ...p, foto: photo } : p) }); toast.success(`Foto protegida e vinculada a ${person.nome}`); } catch (e) { toast.error((e as Error).message); } finally { if (photoInput.current) photoInput.current.value = ""; setPhotoTarget(null); } };
  const uploadEvidence = async (files?: FileList | null) => { if (!selectedItem || !files?.length) return; try { const added = await Promise.all([...files].map((file) => upload(file, selectedItem.id, "evidencia"))); await persist({ ...selectedItem, evidencias: [...selectedItem.evidencias, ...added], historico: [...selectedItem.historico, { data: now(), texto: `${added.length} arquivo(s) anexado(s)` }] }); toast.success("Evidência(s) protegida(s) localmente"); } catch (e) { toast.error((e as Error).message); } finally { if (evidenceInput.current) evidenceInput.current.value = ""; } };
  const openFile = async (file: FileInfo) => { if (!key) return; try { const { data } = await supabase.storage.from("ocorrencia-evidencias").createSignedUrl(file.storagePath, 60); if (!data) throw new Error("Arquivo não encontrado"); const response = await fetch(data.signedUrl); const blob = await decryptFile(await response.blob(), key, file.tipo); URL.revokeObjectURL(data.signedUrl); const url = URL.createObjectURL(blob); if (file.imagem) setViewer({ title: file.nome, url }); else { const link = document.createElement("a"); link.href = url; link.download = file.nome; link.click(); setTimeout(() => URL.revokeObjectURL(url), 2000); } } catch (e) { toast.error((e as Error).message); } };
  const exportSelected = async () => { if (!selectedItem || !key) return; try { const imageFiles = [ ...(includePersonPhotos ? selectedItem.pessoas.flatMap((p) => p.foto ? [{ title: `Foto de ${p.nome}`, file: p.foto }] : []) : []), ...(includeEvidencePhotos ? selectedItem.evidencias.filter((f) => f.imagem).map((file) => ({ title: `Evidência: ${file.nome}`, file })) : []) ]; const images: { titulo: string; dataUrl: string }[] = []; for (const image of imageFiles) { const { data } = await supabase.storage.from("ocorrencia-evidencias").createSignedUrl(image.file.storagePath, 60); if (!data) continue; const response = await fetch(data.signedUrl); const blob = await decryptFile(await response.blob(), key, image.file.tipo); URL.revokeObjectURL(data.signedUrl); images.push({ titulo: image.title, dataUrl: await blobToJpeg(blob) }); } exportOcorrenciaPDF(selectedItem, images); setExportOpen(false); toast.success("PDF gerado localmente"); } catch (e) { toast.error((e as Error).message); } };
  const startEditing = () => { if (!selectedItem) return; setEditDraft({ ...selectedItem, pessoas: [...selectedItem.pessoas], evidencias: [...selectedItem.evidencias], historico: [...selectedItem.historico] }); setEditing(true); };
  const saveEdit = async () => { if (!editDraft || !selectedItem) return; if (!editDraft.local.trim() || !editDraft.categoria.trim() || !editDraft.relato.trim()) return toast.error("Informe local, categoria e relato factual"); try { await persist({ ...editDraft, historico: [...selectedItem.historico, { data: now(), texto: "Informações gerais editadas" }] }); setEditing(false); setEditDraft(null); toast.success("Ocorrência atualizada"); } catch (e) { toast.error((e as Error).message); } };
  if (protection === undefined) return <p className="text-sm text-muted-foreground">Carregando proteção local…</p>;
  if (!protection || !key) return <AccessCard initial={!protection} password={password} confirmation={confirmation} setPassword={setPassword} setConfirmation={setConfirmation} onSubmit={!protection ? setup : unlock} />;
  return <div className="space-y-5">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold flex items-center gap-2"><ShieldAlert className="h-6 w-6 text-primary" /> Ocorrências e Apurações</h1><p className="text-sm text-muted-foreground">Registros factuais protegidos no computador. Esta área não usa internet.</p></div><Button onClick={() => { setDraft(emptyOccurrence()); setNewOpen(true); }}><Plus /> Nova ocorrência</Button></div>
    <div className="grid gap-3 md:grid-cols-3"><Metric title="Em análise" total={items.filter((i) => i.status === "Em análise").length} /><Metric title="Encaminhadas" total={items.filter((i) => i.status === "Encaminhada").length} /><Metric title="Arquivadas" total={items.filter((i) => i.status === "Arquivada").length} /></div>
    <Card><CardContent className="p-4 grid gap-3 md:grid-cols-[1fr_200px]"><div className="relative"><Search className="h-4 w-4 absolute left-3 top-3 text-muted-foreground" /><Input className="pl-9" value={filter} onChange={(e) => setFilter(e.target.value)} placeholder="Pesquisar por protocolo, local, categoria ou relato…" /></div><Select value={statusFilter} onValueChange={setStatusFilter}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="ativos">Ativas (sem arquivadas)</SelectItem><SelectItem value="todos">Todas</SelectItem>{statuses.map((status) => <SelectItem value={status} key={status}>{status}</SelectItem>)}</SelectContent></Select></CardContent></Card>
    <div className="space-y-5"><Card><CardHeader><CardTitle className="text-base">Registros ({shown.length})</CardTitle></CardHeader><CardContent className="space-y-2">{loading ? <p>Carregando…</p> : shown.length === 0 ? <p className="text-sm text-muted-foreground">Nenhuma ocorrência encontrada.</p> : shown.map((item) => <button type="button" onClick={() => setSelected(item.id)} key={item.id} className="w-full rounded-md border p-3 text-left hover:bg-accent"><div className="flex justify-between gap-2"><strong>{item.protocolo}</strong><StatusBadge status={item.status} /></div><p className="text-sm mt-1">{item.categoria || "Sem categoria"} · {item.local || "Local não informado"}</p><p className="text-xs text-muted-foreground mt-1">{item.data} · {item.pessoas.length} pessoa(s) vinculada(s)</p></button>)}</CardContent></Card><Card><CardHeader><CardTitle className="text-base flex gap-2 items-center"><BarChart3 className="h-4 w-4" /> Ocorrências por categoria</CardTitle></CardHeader><CardContent><div className="max-h-[620px] overflow-y-auto pr-2">{stats.length ? <ResponsiveContainer width="100%" height={Math.max(320, stats.length * 42)}><BarChart data={stats} layout="vertical" margin={{ left: 16, right: 24 }}><CartesianGrid strokeDasharray="3 3" stroke="hsl(0 0% 50% / 0.4)" opacity={0.5} /><XAxis type="number" allowDecimals={false} /><YAxis type="category" dataKey="name" width={170} interval={0} /><Tooltip /><Bar dataKey="total" barSize={16} fill="var(--color-chart-1)" radius={[0, 6, 6, 0]} /></BarChart></ResponsiveContainer> : <p className="text-sm text-muted-foreground">Os indicadores aparecerão conforme houver registros.</p>}</div></CardContent></Card></div>
    <Dialog open={newOpen} onOpenChange={setNewOpen}><DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto"><DialogHeader><DialogTitle>Nova ocorrência</DialogTitle></DialogHeader><OccurrenceForm value={draft} onChange={setDraft} /><div className="flex justify-end"><Button onClick={saveNew}><FilePlus2 /> Registrar localmente</Button></div></DialogContent></Dialog>
    <Dialog open={!!selectedItem} onOpenChange={(open) => { if (!open) { setSelected(null); setEditing(false); setEditDraft(null); } }}><DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">{selectedItem && <><DialogHeader><DialogTitle>{editing ? "Editar ocorrência" : selectedItem.protocolo}</DialogTitle></DialogHeader>{editing && editDraft ? <><OccurrenceForm value={editDraft} onChange={setEditDraft} /><div className="flex justify-end gap-2"><Button variant="outline" onClick={() => { setEditing(false); setEditDraft(null); }}>Cancelar</Button><Button onClick={() => void saveEdit()}>Salvar alterações</Button></div></> : <><div className="flex flex-wrap items-center gap-2"><Select value={selectedItem.status} onValueChange={async (value) => { const status = value as Occurrence["status"]; try { await persist({ ...selectedItem, status, historico: [...selectedItem.historico, { data: now(), texto: `Status alterado para ${status}` }] }); } catch (e) { toast.error((e as Error).message); } }}><SelectTrigger className="w-44"><SelectValue /></SelectTrigger><SelectContent>{statuses.map((s) => <SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select><Button variant="outline" onClick={startEditing}><Pencil /> Editar</Button><Button variant="outline" onClick={() => setExportOpen(true)}><FileDown /> Exportar PDF</Button><Button variant="outline" onClick={() => void persist({ ...selectedItem, status: selectedItem.status === "Arquivada" ? "Em análise" : "Arquivada", historico: [...selectedItem.historico, { data: now(), texto: selectedItem.status === "Arquivada" ? "Registro reaberto" : "Registro arquivado" }] })}><Archive /> {selectedItem.status === "Arquivada" ? "Reabrir" : "Arquivar"}</Button></div><div className="grid gap-3 md:grid-cols-2 text-sm"><Info label="Categoria" value={selectedItem.categoria} /><Info label="Local" value={selectedItem.local} /><Info label="Data" value={selectedItem.data} /><Info label="Status" value={selectedItem.status} /></div><Info label="Relato factual" value={selectedItem.relato} block /><Info label="Ações e encaminhamentos" value={selectedItem.encaminhamentos} block />
      <Card><CardHeader><CardTitle className="text-base flex gap-2 items-center"><Users className="h-4 w-4" /> Pessoas vinculadas</CardTitle></CardHeader><CardContent className="space-y-3">{selectedItem.pessoas.map((person) => <div key={person.id} className="flex items-center gap-3 rounded border p-2">{photos[person.id] ? <button type="button" onClick={() => setViewer({ title: person.nome, url: photos[person.id] })}><img className="h-14 w-14 rounded object-cover" src={photos[person.id]} alt={person.nome} /></button> : <div className="h-14 w-14 rounded bg-muted grid place-items-center"><Image className="h-5 w-5" /></div>}<div className="min-w-0 flex-1"><strong>{person.nome}</strong><p className="text-xs text-muted-foreground">{person.tipo}{person.observacao ? ` · ${person.observacao}` : ""}</p></div><Button variant="ghost" size="sm" title="Adicionar ou trocar foto" onClick={() => { setPhotoTarget(person.id); photoInput.current?.click(); }}><Image /></Button></div>)}<div className="grid gap-2 md:grid-cols-3"><Input placeholder="Nome da pessoa" value={personDraft.nome} onChange={(e) => setPersonDraft({ ...personDraft, nome: e.target.value })} /><Select value={personDraft.tipo} onValueChange={(tipo) => setPersonDraft({ ...personDraft, tipo: tipo as Person["tipo"] })}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="Colaborador terceirizado">Colaborador terceirizado</SelectItem><SelectItem value="Pessoa externa">Pessoa externa</SelectItem><SelectItem value="Outro">Outro</SelectItem></SelectContent></Select><Button variant="outline" onClick={addPerson}><Plus /> Vincular</Button></div><div className="flex gap-2"><input ref={photoInput} onChange={(e) => void uploadPersonPhoto(e.target.files?.[0])} type="file" accept="image/*" className="hidden" /><span className="text-xs text-muted-foreground self-center">Use o ícone de imagem em cada pessoa; clique na foto para ampliá-la.</span></div></CardContent></Card>
      <Card><CardHeader><CardTitle className="text-base">Arquivos e evidências</CardTitle></CardHeader><CardContent className="space-y-2"><input ref={evidenceInput} type="file" multiple className="hidden" onChange={(e) => void uploadEvidence(e.target.files)} /><Button variant="outline" size="sm" onClick={() => evidenceInput.current?.click()}><FolderOpen /> Anexar arquivo</Button>{selectedItem.evidencias.map((file) => <button type="button" key={file.id} onClick={() => void openFile(file)} className="flex w-full justify-between rounded border p-2 text-left text-sm hover:bg-accent"><span>{file.nome}</span><span className="text-muted-foreground">{file.imagem ? "Visualizar" : "Baixar"}</span></button>)}</CardContent></Card>
      <Card><CardHeader><CardTitle className="text-base">Histórico</CardTitle></CardHeader><CardContent>{selectedItem.historico.slice().reverse().map((entry) => <p className="text-xs py-1" key={`${entry.data}${entry.texto}`}><span className="text-muted-foreground">{new Date(entry.data).toLocaleString("pt-BR")}</span> — {entry.texto}</p>)}</CardContent></Card></>}</>}</DialogContent></Dialog>
    <Dialog open={!!viewer} onOpenChange={(open) => !open && setViewer(null)}><DialogContent className="max-w-3xl"><DialogHeader><DialogTitle>{viewer?.title}</DialogTitle></DialogHeader>{viewer && <img src={viewer.url} alt={viewer.title} className="max-h-[70vh] w-full object-contain" />}</DialogContent></Dialog>
    <Dialog open={exportOpen} onOpenChange={setExportOpen}><DialogContent><DialogHeader><DialogTitle>Exportar ocorrência em PDF</DialogTitle></DialogHeader><label className="flex gap-2 text-sm"><input type="checkbox" checked={includePersonPhotos} onChange={(e) => setIncludePersonPhotos(e.target.checked)} /> Incluir fotos das pessoas</label><label className="flex gap-2 text-sm"><input type="checkbox" checked={includeEvidencePhotos} onChange={(e) => setIncludeEvidencePhotos(e.target.checked)} /> Incluir imagens de evidências</label><p className="text-xs text-muted-foreground">Arquivos não visuais serão listados no relatório; fotos e imagens podem aumentar o tamanho do PDF.</p><Button onClick={() => void exportSelected()}>Gerar PDF</Button></DialogContent></Dialog>
  </div>;
}

function AccessCard({ initial, password, confirmation, setPassword, setConfirmation, onSubmit }: { initial: boolean; password: string; confirmation: string; setPassword: (v: string) => void; setConfirmation: (v: string) => void; onSubmit: () => void }) { return <div className="mx-auto max-w-md pt-10"><Card><CardHeader><CardTitle className="flex gap-2"><LockKeyhole /> {initial ? "Proteger Ocorrências e Apurações" : "Desbloquear Ocorrências e Apurações"}</CardTitle></CardHeader><CardContent className="space-y-3"><p className="text-sm text-muted-foreground">{initial ? "Defina uma senha exclusiva desta aba. Registros, fotos e evidências serão cifrados antes de serem gravados no computador. A senha não é guardada e não cria login para o SPGuard." : "Informe a senha exclusiva desta área. Os demais módulos do SPGuard continuam sem login."}</p><Label>Senha</Label><Input type="password" value={password} onChange={(e) => setPassword(e.target.value)} onKeyDown={(e) => e.key === "Enter" && onSubmit()} autoFocus />{initial && <><Label>Confirmar senha</Label><Input type="password" value={confirmation} onChange={(e) => setConfirmation(e.target.value)} onKeyDown={(e) => e.key === "Enter" && onSubmit()} /></>}<Button className="w-full" onClick={onSubmit}><KeyRound /> {initial ? "Criar proteção" : "Desbloquear"}</Button>{initial && <p className="text-xs text-muted-foreground">Use ao menos 12 caracteres. Se a senha for esquecida, os dados desta área não poderão ser lidos.</p>}</CardContent></Card></div>; }
function Metric({ title, total }: { title: string; total: number }) { return <Card><CardContent className="p-4"><p className="text-xs text-muted-foreground">{title}</p><p className="text-2xl font-bold">{total}</p></CardContent></Card>; }
function StatusBadge({ status }: { status: Occurrence["status"] }) { const styles: Record<Occurrence["status"], string> = { "Em análise": "border-amber-500/40 bg-amber-500/15 text-amber-700 dark:text-amber-300", Encaminhada: "border-blue-500/40 bg-blue-500/15 text-blue-700 dark:text-blue-300", Encerrada: "border-emerald-500/40 bg-emerald-500/15 text-emerald-700 dark:text-emerald-300", Arquivada: "border-slate-500/40 bg-slate-500/15 text-slate-700 dark:text-slate-300" }; return <Badge variant="outline" className={styles[status]}>{status}</Badge>; }
function Info({ label, value, block }: { label: string; value: string; block?: boolean }) { return <div className={block ? "rounded border p-3" : ""}><p className="text-xs text-muted-foreground">{label}</p><p className="whitespace-pre-wrap text-sm">{value || "-"}</p></div>; }
function OccurrenceForm({ value, onChange }: { value: Occurrence; onChange: (next: Occurrence) => void }) { const set = (field: keyof Occurrence, val: string) => onChange({ ...value, [field]: val }); return <div className="grid gap-3 md:grid-cols-2"><div><Label>Protocolo</Label><Input value={value.protocolo} onChange={(e) => set("protocolo", e.target.value)} /></div><div><Label>Data</Label><Input type="date" value={value.data} onChange={(e) => set("data", e.target.value)} /></div><div><Label>Local</Label><Input value={value.local} onChange={(e) => set("local", e.target.value)} /></div><div><Label>Categoria</Label><Input list="categorias-ocorrencia" value={value.categoria} onChange={(e) => set("categoria", e.target.value)} /><datalist id="categorias-ocorrencia">{categories.map((c) => <option value={c} key={c} />)}</datalist></div><div className="md:col-span-2"><Label>Relato factual</Label><Textarea value={value.relato} onChange={(e) => set("relato", e.target.value)} placeholder="Descreva somente os fatos observados: o que ocorreu, quem comunicou, data, horário, local e circunstâncias. Evite conclusões ou acusações sem comprovação." /></div><div className="md:col-span-2"><Label>Ações e encaminhamentos</Label><Textarea value={value.encaminhamentos} onChange={(e) => set("encaminhamentos", e.target.value)} placeholder="Registre as providências adotadas, responsáveis, comunicações realizadas, documentos consultados e os próximos passos necessários." /></div></div>; }
async function blobToJpeg(blob: Blob) { const url = URL.createObjectURL(blob); try { const image = await new Promise<HTMLImageElement>((resolve, reject) => { const element = new window.Image(); element.onload = () => resolve(element); element.onerror = reject; element.src = url; }); const max = 1400; const scale = Math.min(1, max / image.width, max / image.height); const canvas = document.createElement("canvas"); canvas.width = Math.max(1, Math.round(image.width * scale)); canvas.height = Math.max(1, Math.round(image.height * scale)); canvas.getContext("2d")?.drawImage(image, 0, 0, canvas.width, canvas.height); return canvas.toDataURL("image/jpeg", 0.82); } finally { URL.revokeObjectURL(url); } }
