/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedEmpresasRouteImport } from './routes/_authenticated/empresas'
import { Route as AuthenticatedEletronicosRouteImport } from './routes/_authenticated/eletronicos'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConsultaRouteImport } from './routes/_authenticated/consulta'
import { Route as AuthenticatedColaboradoresRouteImport } from './routes/_authenticated/colaboradores'
import { Route as AuthenticatedOcorrenciasRouteImport } from './routes/_authenticated/ocorrencias'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEmpresasRoute = AuthenticatedEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEletronicosRoute =
  AuthenticatedEletronicosRouteImport.update({
    id: '/eletronicos',
    path: '/eletronicos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConsultaRoute = AuthenticatedConsultaRouteImport.update({
  id: '/consulta',
  path: '/consulta',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedColaboradoresRoute =
  AuthenticatedColaboradoresRouteImport.update({
    id: '/colaboradores',
    path: '/colaboradores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOcorrenciasRoute =
  AuthenticatedOcorrenciasRouteImport.update({
    id: '/ocorrencias',
    path: '/ocorrencias',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/colaboradores': typeof AuthenticatedColaboradoresRoute
  '/consulta': typeof AuthenticatedConsultaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/eletronicos': typeof AuthenticatedEletronicosRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/ocorrencias': typeof AuthenticatedOcorrenciasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/colaboradores': typeof AuthenticatedColaboradoresRoute
  '/consulta': typeof AuthenticatedConsultaRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/eletronicos': typeof AuthenticatedEletronicosRoute
  '/empresas': typeof AuthenticatedEmpresasRoute
  '/ocorrencias': typeof AuthenticatedOcorrenciasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/colaboradores': typeof AuthenticatedColaboradoresRoute
  '/_authenticated/consulta': typeof AuthenticatedConsultaRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/eletronicos': typeof AuthenticatedEletronicosRoute
  '/_authenticated/empresas': typeof AuthenticatedEmpresasRoute
  '/_authenticated/ocorrencias': typeof AuthenticatedOcorrenciasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/colaboradores'
    | '/consulta'
    | '/dashboard'
    | '/eletronicos'
    | '/empresas'
    | '/ocorrencias'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/colaboradores'
    | '/consulta'
    | '/dashboard'
    | '/eletronicos'
    | '/empresas'
    | '/ocorrencias'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/colaboradores'
    | '/_authenticated/consulta'
    | '/_authenticated/dashboard'
    | '/_authenticated/eletronicos'
    | '/_authenticated/empresas'
    | '/_authenticated/ocorrencias'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/empresas': {
      id: '/_authenticated/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AuthenticatedEmpresasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/eletronicos': {
      id: '/_authenticated/eletronicos'
      path: '/eletronicos'
      fullPath: '/eletronicos'
      preLoaderRoute: typeof AuthenticatedEletronicosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/consulta': {
      id: '/_authenticated/consulta'
      path: '/consulta'
      fullPath: '/consulta'
      preLoaderRoute: typeof AuthenticatedConsultaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/colaboradores': {
      id: '/_authenticated/colaboradores'
      path: '/colaboradores'
      fullPath: '/colaboradores'
      preLoaderRoute: typeof AuthenticatedColaboradoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ocorrencias': {
      id: '/_authenticated/ocorrencias'
      path: '/ocorrencias'
      fullPath: '/ocorrencias'
      preLoaderRoute: typeof AuthenticatedOcorrenciasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedColaboradoresRoute: typeof AuthenticatedColaboradoresRoute
  AuthenticatedConsultaRoute: typeof AuthenticatedConsultaRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEletronicosRoute: typeof AuthenticatedEletronicosRoute
  AuthenticatedEmpresasRoute: typeof AuthenticatedEmpresasRoute
  AuthenticatedOcorrenciasRoute: typeof AuthenticatedOcorrenciasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedColaboradoresRoute: AuthenticatedColaboradoresRoute,
  AuthenticatedConsultaRoute: AuthenticatedConsultaRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEletronicosRoute: AuthenticatedEletronicosRoute,
  AuthenticatedEmpresasRoute: AuthenticatedEmpresasRoute,
  AuthenticatedOcorrenciasRoute: AuthenticatedOcorrenciasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
